### ISSUE TITLE
Use rustup.rs instead of the deprecated rustup.sh

### ISSUE THREAD

**Issue by glebm** [code-lever/asdf-rust#12]
rustup.sh is very old and is missing some crucial features.

rustup.rs installation can be based on this script: https://sh.rustup.rs

**Comment by vifino** [comment]
Yeah, this is quite a big problem. RLS, rust-src and all.

**Comment by nickveys** [comment]
I'd be happy to mess with getting this working but since the script @ https://sh.rustup.rs is itself an installer for the tool to manage toolchains, it would kind of be redundant with asdf would it not?  I haven't looked enough into it to know if asdf could effectively manage this.

**Comment by x80486** [comment]
`asdf` would be somehow a "wrapper" for that installation script itself. Anyhow, that's the case for some (of the `asdf`) installers, right?

Is it possible to udpate this one to use the latest? Right now it doesn't install the sources and things like that.

Thanks in advance!

**Comment by b1-88er** [comment]
Is there any workaround for this?

**Comment by nickveys** [comment]
#13 seems to fix this, feel free to report any issues if they come up!
