### ISSUE TITLE
Shims fail if no arguments are passed

### ISSUE THREAD

**Issue by calebmeyer** [code-lever/asdf-rust#17]
## Steps to reproduce

Install rust:
```
asdf plugin-add rust
asdf install rust stable
```

Run rust without arguments:
```
rustc
```

## Expected behavior

It prints out the help messages of rustc.

## Actual behavior
```
/Users/cm022291/.asdf/lib/commands/shim-exec.sh: line 21: shim_args[@]: unbound variable
```

### Environment
*OS*: macOS 10.14.5
*asdf version*: v0.7.4, install from git.

P.S. python, ruby, node, yarn installed from asdf all work well without arguments. Cargo exhibits same behavior as rustc

P.P.S. I shamelessly stole this template from https://github.com/asdf-vm/asdf/issues/522

**Comment by yofriadi** [comment]
got the same error here

**Comment by nickveys** [comment]
Looks like #19 takes care of this.
