### ISSUE TITLE
Support for nightly?

### ISSUE THREAD

**Issue by jc00ke** [code-lever/asdf-rust#2]
Some projects (like [Rockets](https://rocket.rs)) suggest using `nightly`. `rustup` supports this nicely, was wondering if you had interest in supporting it here?

**Comment by nickveys** [comment]
I don't think asdf has an "update" function, which would be needed to keep the nightly fresh.  Of course you could just uninstall/install.

I haven't tried adding support for it but if you have/have a PR that adds it I'm game.

**Comment by jc00ke** [comment]
`asdf install rust nightly` would be OK with me. I'll see if I can get something going, no promises :wink:

**Comment by Quintasan** [comment]
I created a disgustingly simple PR #4. I believe that we now have to have update functionality into asdf itself. I'll be looking into that next weekend if someone doesn't beat me to it.

**Comment by nickveys** [comment]
At the very least you can uninstall/install to get the latest...  It'll work for now. :)
