### ISSUE TITLE
Add support for default cargo packages

### ISSUE THREAD

**Issue by jackmac92** [code-lever/asdf-rust#20]
Any interest in supporting a "download default cargo packages" post install hook? I find it helpful in the asdf-node and asdf-python packages.

e.g.
https://github.com/danhper/asdf-python/blob/b544ac9e512b1d95ad80d432b47b181be40199c0/bin/install#L23

**Comment by jackmac92** [comment]
I'll make a PR if you'd accept

**Comment by nickveys** [comment]
For sure, we'll take PR with that.  Thanks!

**Comment by nickveys** [comment]
Fixed by #21.
