### ISSUE TITLE
[Question] How to do rustup upgrades?

### ISSUE THREAD

**Issue by x80486** [code-lever/asdf-rust#25]
This is probably silly, but how do we upgrade `rustup` with the ASDF plugin? Just `rustup update`?

I'm just asking because I have no idea if that would mess up something else installed initially by ASDF, or any references needed to uninstall, etc.

**Comment by tony** [comment]
@x80486 what was the solution found?

When updating through `~/.tool-versions`  + `asdf install` I get:


```
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /home/t/.config/.asdf/shims
warning: rustup should not be installed alongside Rust. Please uninstall your existing Rust first.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed
warning: continuing (because the -y flag is set and the error is ignorable)
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for '1.52.1-x86_64-unknown-linux-gnu'
info: latest update on 2021-05-10, rust version 1.52.1 (9bc8c42bb 2021-05-09)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
```

**Comment by x80486** [comment]
@tony, that was exactly the reason for my question. I ended up uninstalling and installing...all via `asdf` anyway.

**Comment by tony** [comment]
@x80486 Same. I reset my installation of asdf due to other issues affecting it too (not sure what the real cause was, but likely rust installations competing with each other and accrued symlinks experimenting with `asdf` / `rustup` / etc)
